document.addEventListener("DOMContentLoaded",function(){let e=document.querySelector(".nav-btn"),t=document.querySelector(".filter-btn"),n=document.querySelector(".menu"),s=document.querySelector(".filters-menu"),o=document.querySelector(".link1"),r=document.querySelector(".link2"),a=document.querySelector(".link3"),l=document.querySelector(".link4"),c=document.querySelector(".menu-subnav-content"),i=document.querySelector(".menu-subnav-content2"),d=document.querySelector(".menu-subnav-content3"),u=document.querySelector(".menu-subnav-content4"),f=document.querySelectorAll(".flex-arrow a"),p=document.querySelectorAll(".menu-subnav svg"),m=document.querySelector(".filter-btn svg"),g=document.getElementById("es_form_f2-n1"),v=document.getElementById("es_form_f2-n3");if(g){let y=g.querySelector(".es_subscription_message.success");if(y){let L=document.createElement("div");L.classList.add("modal"),L.innerHTML=`
              <div class="modal-content">
                  <span class="close">&times;</span>
                  <h2>Thank You For Joining Our Newsletter</h2>
                  <p id="successMessage">Thank you for joining our newsletter we will send out updates on events and in-store offers.</p>
              </div>
          `,g.appendChild(L),L.style.display="block";let h=L.querySelector(".close");h.addEventListener("click",function(){L.style.display="none"}),window.addEventListener("click",function(e){e.target==L&&(L.style.display="none")})}}if(v){let k=v.querySelector(".es_subscription_message.success");if(k){let S=document.createElement("div");S.classList.add("modal"),S.innerHTML=`
            <div class="modal-content">
                <span class="close">&times;</span>
                <h2>Thank You For Joining Our Newsletter</h2>
                <p id="successMessage">Thank you for joining our newsletter we will send out updates on events and in-store offers.</p>
            </div>
        `,v.appendChild(S),S.style.display="block";let w=S.querySelector(".close");w.addEventListener("click",function(){S.style.display="none"}),window.addEventListener("click",function(e){e.target==S&&(S.style.display="none")})}}document.addEventListener("DOMContentLoaded",function(){checkSubscriptionStatus()}),f.length>0&&p.length>0&&f.length===p.length?f.forEach((e,t)=>{e.addEventListener("click",function(e){e.preventDefault(),p[t].classList.toggle("rotate180")})}):console.error("Links or SVGs not found or mismatched."),m&&t.addEventListener("click",function(){m.classList.toggle("rotate180")}),e&&n?e.addEventListener("click",function(){n.classList.toggle("menu-expanded")}):console.error("Nav button or menu not found."),o&&c?o.addEventListener("click",function(){c.classList.toggle("menu-expanded-small")}):console.error("Subnav or menu content not found."),r&&i?r.addEventListener("click",function(){i.classList.toggle("menu-expanded-small")}):console.error("Subnav 2 or menu content 2 not found."),a&&d?a.addEventListener("click",function(){d.classList.toggle("menu-expanded-small")}):console.error("Subnav 3 or menu content 3 not found."),l&&u?l.addEventListener("click",function(){u.classList.toggle("menu-expanded-small")}):console.error("Subnav 4 or menu content 4 not found."),t&&s&&t.addEventListener("click",function(){s.classList.toggle("wpf_form_expand")}),$(document).ready(function(){window.location.href.includes("wpf=filters")&&$(".woocommerce-pagination").on("click","a",function(e){e.preventDefault();var t=$(this).text().trim(),n=window.location.href,s=new URL(n);if("next"===t.toLowerCase()){var o=parseInt(s.searchParams.get("wpf_page"))||1;s.searchParams.set("wpf_page",o+1)}else if("prev"===t.toLowerCase()){var o=parseInt(s.searchParams.get("wpf_page"))||1;s.searchParams.set("wpf_page",Math.max(o-1,1))}else s.searchParams.set("wpf_page",t);window.location.href=s.toString()})})}),document.addEventListener("DOMContentLoaded",function(){document.addEventListener("click",function(e){e.target.matches('.wpf_reset_btn input[type="reset"]')&&(window.location.href="https://pacesetter-a.web.dmitcapstone.ca/wordpress/shop/")})});